name: ROS2 CI

on:
  push:
    branches: [ main, real-robot ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ROS2
        run: |
          sudo apt update
          sudo apt install -y ros-humble-desktop

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
